### ISSUE TITLE
tensorflow-converted model failed in demo.py with 'KeyError'

### ISSUE THREAD

**Issue by MichaelLiang12** [ruotianluo/pytorch-faster-rcnn#25]
I first convert from tf-faster-rcnn model. [http://xinlei.sp.cs.cmu.edu/xinleic/tf-faster-rcnn/res101/voc_2007_50-70k.tgz](http://xinlei.sp.cs.cmu.edu/xinleic/tf-faster-rcnn/res101/voc_2007_50-70k.tgz)  & [http://xinlei.sp.cs.cmu.edu/xinleic/tf-faster-rcnn/vgg16/voc_2007_50k-70k.tgz](http://xinlei.sp.cs.cmu.edu/xinleic/tf-faster-rcnn/vgg16/voc_2007_50k-70k.tgz) and run tool/demo.py, but failed with: (ubuntu14.04, cuda8.0, cudnn6, python3.6)

res101+pascal_voc
```
Traceback (most recent call last):
  File "tools/demo.py", line 143, in <module>
    net.load_state_dict(torch.load(saved_model))
  File "/home/ljy/pytorch-examples-master/pytorch-faster-rcnn-master/tools/../lib/nets/network.py", line 481, in load_state_dict
    nn.Module.load_state_dict(self, {k: state_dict[k] for k in list(self.state_dict())})
  File "/home/ljy/pytorch-examples-master/pytorch-faster-rcnn-master/tools/../lib/nets/network.py", line 481, in <dictcomp>
    nn.Module.load_state_dict(self, {k: state_dict[k] for k in list(self.state_dict())})
KeyError: 'resnet.bn1.bias'
```
vgg16+pascal_voc
```
Traceback (most recent call last):
  File "tools/demo.py", line 143, in <module>
    net.load_state_dict(torch.load(saved_model))
  File "/home/ljy/pytorch-examples-master/pytorch-faster-rcnn-master/tools/../lib/nets/network.py", line 481, in load_state_dict
    nn.Module.load_state_dict(self, {k: state_dict[k] for k in list(self.state_dict())})
  File "/home/ljy/pytorch-examples-master/pytorch-faster-rcnn-master/tools/../lib/nets/network.py", line 481, in <dictcomp>
    nn.Module.load_state_dict(self, {k: state_dict[k] for k in list(self.state_dict())})
KeyError: 'vgg.features.14.bias'
```

Something wrong with tensorflow-converted model?

**Comment by ruotianluo** [comment]
I guess they may recently updated their model?

**Comment by ruotianluo** [comment]
I will take a look

**Comment by ruotianluo** [comment]
I do have these keys in my converted file?

**Comment by MichaelLiang12** [comment]
Yes, I download models from [https://github.com/endernewton/tf-faster-rcnn/#demo-and-test-with-pre-trained-models](https://github.com/endernewton/tf-faster-rcnn/#demo-and-test-with-pre-trained-models) and convert it using 
```
python tools/convert_from_tensorflow.py --tensorflow_model resnet_model.ckpt 
```
BTW, I fixed the  bugs in `tools/convert_from_tensorflow.py` according to #20

**Comment by ruotianluo** [comment]
Fixed in recent commits.

**Comment by MichaelLiang12** [comment]
I updated with recent commits and downloaded `res101_faster_rcnn_iter_70000.pth` from GoogleDrive, but I failed with the same problem. `KeyError: 'vgg.features.14.bias'`

**Comment by ruotianluo** [comment]
are you converting from tensorflow model or using pytorch model?

**Comment by MichaelLiang12** [comment]
Sorry, I made some mistakes. The final conclusion are as follows:
1, models converted from tensroflow(Downloaded from [https://github.com/endernewton/tf-faster-rcnn/#demo-and-test-with-pre-trained-models](https://github.com/endernewton/tf-faster-rcnn/#demo-and-test-with-pre-trained-models)) still failed
2, models downloaded from provided GoogleDrive(pytorch model, [https://drive.google.com/open?id=0B7fNdx_jAqhtNE10TDZDbFRuU0E](https://drive.google.com/open?id=0B7fNdx_jAqhtNE10TDZDbFRuU0E)) succeed
Thank you!

**Comment by ruotianluo** [comment]
So you fixed it by adding wrapping all the var_dict.keys() with list?

**Comment by MichaelLiang12** [comment]
No, I downloaded pytorch model from GoogleDrive and ran `demo.py` successfully. 

It seems that you have fixed `convert_from_tensorflow.py`. Thus I can convert tensorflow-model to pytorch-model without error. But tensorflow-converted models still lead to the same problem `KeyError: 'resnet.bn1.bias'`.

**Comment by ruotianluo** [comment]
My bad, will fix it in one min.

**Comment by MichaelLiang12** [comment]
Wrapping all the var_dict.keys() with list in `convert_from_tensorflow.py` works!

**Comment by StayMeBYp** [comment]
mmap@mmap01:~/godblessme/pytorch-faster-rcnn$ CUDA_VISIBLE_DEVICES=${GPU_ID} ./tools/demo.py
Traceback (most recent call last):
  File "./tools/demo.py", line 139, in <module>
    net.load_state_dict(torch.load(saved_model, map_location=lambda storage, loc: storage))
  File "/home/mmap/godblessme/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 490, in load_state_dict
    nn.Module.load_state_dict(self, {k: state_dict[k] for k in list(self.state_dict())})
  File "/home/mmap/godblessme/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 490, in <dictcomp>
    nn.Module.load_state_dict(self, {k: state_dict[k] for k in list(self.state_dict())})
KeyError: 'resnet.bn1.num_batches_tracked'

**Comment by StayMeBYp** [comment]
Could you give me some suggestions? Thank you very much.

**Comment by StayMeBYp** [comment]
mmap@mmap01:~/godblessme/pytorch-faster-rcnn$ python ./tools/demo.py --net vgg16 --dataset pascal_voc
Traceback (most recent call last):
  File "./tools/demo.py", line 139, in <module>
    net.load_state_dict(torch.load(saved_model, map_location=lambda storage, loc: storage))
  File "/home/mmap/godblessme/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 490, in load_state_dict
    nn.Module.load_state_dict(self, {k: state_dict[k] for k in list(self.state_dict())})
  File "/home/mmap/godblessme/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 490, in <dictcomp>
    nn.Module.load_state_dict(self, {k: state_dict[k] for k in list(self.state_dict())})
KeyError: 'vgg.features.0.weight'

**Comment by StayMeBYp** [comment]
They both didn't work.
